format_version = 3

[apps.MarinaUI]
identifier = "dev.bcollard.MarinaUI"
product = "MarinaUI"
version = "0.3.0"
category = "public.app-category.developer-tools"
icon = "Sources/MarinaUI/Resources/marina-logo.png"

[apps.MarinaUI.plist]
CFBundleDisplayName = "Marina"
CFBundleName = "Marina"
NSHumanReadableCopyright = "Copyright © 2026 Baptiste Collard. All rights reserved."
LSMinimumSystemVersion = "14.0"
NSHighResolutionCapable = true
